site_name: Fuyao's Blog

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: zh
  palette: 
    - scheme: custom
      primary: red
      accent: red
      toggle:
        name: Switch to light mode
        icon: material/brightness-7
    - scheme: slate
      primary: red
      accent: red
      toggle:
        name: Switch to dark mode
        icon: material/brightness-4

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.follow
    # - header.autohide
    # - content.action.edit
    # - content.action.view

repo_url: https://github.com/Fuyao233/Fuyao.github.io
repo_name: Fuyao.github.io

edit_uri: edit/main/docs/




extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fuyao233
      name: My Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:yinghaocai@foxmail.com
      name: My Email
  
nav:
  - Home: index.md
  - 环境: 
    - Linux下安装Gecode: 环境/gecode安装.md
    - Linux下安装Matlab: 环境/linux安装matlab.md
    - 无root权限安装cmake: 环境/无root权限安装cmake.md
  - 其他:
    - Git问题汇总:  环境/git问题汇总.md
    - Python小技巧: 其他/python.md
    - Pytorch随笔: 其他/Pytorch.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      auto_title: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
