site_name: Fuyao's Blog

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: zh
  palette: 
    - scheme: custom
      primary: red
      accent: red
      toggle:
        name: Switch to light mode
        icon: material/brightness-7
    - scheme: slate
      primary: red
      accent: red
      toggle:
        name: Switch to dark mode
        icon: material/brightness-4

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.follow
    # - header.autohide
    # - content.action.edit
    # - content.action.view

repo_url: https://github.com/Fuyao233/Fuyao.github.io
repo_name: Fuyao.github.io

edit_uri: edit/main/docs/




extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Fuyao233
      name: My Github
    - icon: fontawesome/solid/paper-plane
      link: mailto:yinghaocai@foxmail.com
      name: My Email
  
